server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost/local

---
spring:
  kafka:
    listener:
      concurrency: 3
    consumer:
      topic: MultiPart2Replica2Topic
      client-id: 1
      auto-offset-reset: earliest
      bootstrap-servers: "localhost:9092, localhost:9093, localhost:9094"
      group-id: json_group
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: "localhost:9092, localhost:9093, localhost:9094"
      retries: 3
      acks: 1
